# ==============================
# Aegis-3 Custom Rules Entry
# ==============================

Include /etc/nginx/rules/aegis3-00-healthcheck.conf
Include /etc/nginx/rules/aegis3-10-shadow-api.conf
Include /etc/nginx/rules/aegis3-20-api-policy.conf
Include /etc/nginx/rules/aegis3-30-internal-protection.conf
Include /etc/nginx/rules/aegis3-40-auth-policy.conf
Include /etc/nginx/rules/aegis3-50-mass-assignment.conf
Include /etc/nginx/rules/aegis3-60-recon-scanner.conf
