version: '3.8'

services:
  # 프록시 서버 (Node.js) - 모든 트래픽의 입구
  aegis-proxy:
    build: ./proxy
    restart: always # 서버 다운 방지
    ports:
      - '80:80'
    environment:
      - DB_HOST=aegis-db
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - MONGO_URI=mongodb://aegis_user:${MONGO_PASSWORD}@aegis-mongodb:27017/aegis_logs
      - REDIS_HOST=aegis-redis
    depends_on:
      - aegis-db
      - aegis-mongodb
      - aegis-redis


  # PostgreSQL (라우팅 정보)
  aegis-db:
    image: postgres:15
    restart: always # 서버 다운 방지
    environment:
      POSTGRES_USER: aegis_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aegis_proxy
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

  # MongoDB (로그 저장)
  aegis-mongodb:
    image: mongo:latest
    restart: always # 서버 다운 방지
    environment:
      MONGO_INITDB_ROOT_USERNAME: aegis_user
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data/mongo:/data/db

  # Redis (캐시)
  aegis-redis:
    image: redis:latest
    restart: always # 서버 다운 방지
