# 동적 모듈 로드 (빌드된 경로 확인 필수)
# load_module /usr/local/nginx/modules/ngx_http_coraza_module.so;

user root;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # 이지스-3 WAF 엔진 활성화
    # coraza on;
    # 규칙 파일 경로 (실행 시 이 경로에 파일이 있어야 함)
    # coraza_rules_file /etc/nginx/coraza.conf;

    server {
        listen       80;
        server_name  localhost;

        location / {
            # 도커로 실행 중인 이지스 프록시(Port 3000)로 전달
            proxy_pass http://proxy:3000;
            
            # --- [개인정보 마스킹 미들웨어] ---
            sub_filter_once off;
            sub_filter_types application/json text/html;
            sub_filter '010-9999-8888' '010-9999-****';
            sub_filter '900101-1234567' '900101-1******';

            # 마스킹 작동을 위한 필수 헤더 설정
            proxy_set_header Accept-Encoding ""; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
